### ISSUE TITLE
Fails on "no such file" - /kids-movies

### ISSUE THREAD

**Issue by briankavanaugh** [anthonysnyder/backgroundarr#4]
It looks like app.py expects these directories to exist:
"/movies", "/kids-movies", "/movies2", "/kids-movies2"

I only have the first one. Not sure on the TV files, because I don't get that far, but there I only have "/tv". But, after starting it if I try to access the app I get the following:

backgroundarr | [2025-01-27 22:29:11,166] ERROR in app: Exception on / [GET]
backgroundarr | Traceback (most recent call last):
backgroundarr |   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
backgroundarr |     response = self.full_dispatch_request()
backgroundarr |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backgroundarr |   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
backgroundarr |     rv = self.handle_user_exception(e)
backgroundarr |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backgroundarr |   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
backgroundarr |     rv = self.dispatch_request()
backgroundarr |          ^^^^^^^^^^^^^^^^^^^^^^^
backgroundarr |   File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
backgroundarr |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
backgroundarr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backgroundarr |   File "/app/app.py", line 175, in index
backgroundarr |     movies, total_movies = get_backdrop_thumbnails(movie_folders)
backgroundarr |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backgroundarr |   File "/app/app.py", line 120, in get_backdrop_thumbnails
backgroundarr |     for media_dir in sorted(os.listdir(base_folder)):
backgroundarr |                             ^^^^^^^^^^^^^^^^^^^^^^^
backgroundarr | FileNotFoundError: [Errno 2] No such file or directory: '/kids-movies'

Line 120 is trying to list the directory without checking whether it exists, first.

**Comment by anthonysnyder** [comment]
I THINK I fixed this this morning with an update to the Docker Compose I have listed in the README. 

You can add or remove whatever Volumes you have in your setup.

**Comment by briankavanaugh** [comment]
The docker compose only lists Movies and TV, true, but app.py has the directories hard coded arrays in lines 28 and 29. I don't know python well enough to really read the file, but I see that line 115 defaults to the movies array if nothing is passed to it. That seems to be what is happening to me.

Here's my docker compose:
```
services:
  postarr:
    image: swguru2004/backgroundarr:latest
    container_name: backgroundarr
    ports:
      - "1596:5000"
    environment:
      - TMDB_API_KEY=<>
      - PUID=1000
      - PGID=1000
#      - SLACK_WEBHOOK_URL=your_slack_webhook_url_here
    volumes:
      - /mnt/video/Movies:/movies
      - /mnt/video/TV/Shows:/tv
    networks:
      - bridge_network

networks:
  bridge_network:
    driver: bridge

```
