### ISSUE TITLE
Question about movie and tv directories

### ISSUE THREAD

**Issue by tucker19** [anthonysnyder/backgroundarr#7]
Is it possible to be able to pass a single "media" directory to then within Backgroundarr to map Movies and TV paths? I currently have different directories for Movies, TV Shows, Anime, Anime Movies and Documentaries. Would be nice if I didnt have to add each of those lines to the compose.

**Comment by tucker19** [comment]
Main reason I ask is I have all my media on a separate NAS that I have linked via a Docker Volume
```
volumes:
  drivepool:
    driver_opts:
      type: cifs
      o: "username=$SYN_USR,password=$SYN_PASS,rw,uid=1000,gid=1000"
      device: "//192.168.86.113/Plex\ Media"
```

and doing the drill down within compose keeps causing a `NoneType` error when looking for directories
